import Foundation

enum RealtimeSemanticEagerness: String {
    case low
    case medium
    case high
    case automatic = "auto"
}

enum RealtimeVoiceActivityDetection {
    case semantic(eagerness: RealtimeSemanticEagerness = .automatic)
    case server(
        threshold: Double = 0.5,
        prefixPaddingMilliseconds: Int = 300,
        silenceDurationMilliseconds: Int = 500
    )

    fileprivate var eventObject: [String: Any] {
        switch self {
        case .semantic(let eagerness):
            return [
                "type": "semantic_vad",
                "eagerness": eagerness.rawValue,
                "create_response": true,
                "interrupt_response": true,
            ]
        case .server(let threshold, let prefixPadding, let silenceDuration):
            return [
                "type": "server_vad",
                "threshold": min(1, max(0, threshold)),
                "prefix_padding_ms": max(0, prefixPadding),
                "silence_duration_ms": max(100, silenceDuration),
                "create_response": true,
                "interrupt_response": true,
            ]
        }
    }
}

/// Aurora protects the beginning of each spoken turn with explicit server-side
/// prefix audio. Semantic VAD has no supported prefix-padding control, which
/// made a quiet first word vulnerable to being omitted from the committed turn.
enum AuroraVoiceActivityProfile {
    static let live = RealtimeVoiceActivityDetection.server(
        threshold: 0.5,
        prefixPaddingMilliseconds: 600,
        silenceDurationMilliseconds: 500
    )
}

struct RealtimeSessionConfiguration {
    let apiKey: String
    let instructions: String
    let toolsJSON: String
    let vad: RealtimeVoiceActivityDetection

    init(
        apiKey: String,
        instructions: String,
        toolsJSON: String = "[]",
        vad: RealtimeVoiceActivityDetection = AuroraVoiceActivityProfile.live
    ) {
        self.apiKey = apiKey
        self.instructions = instructions
        self.toolsJSON = toolsJSON
        self.vad = vad
    }
}

struct RealtimeFunctionCall {
    let connectionID: UUID
    let responseID: String
    /// The committed user audio item that caused this response, when one
    /// exists. Tool continuations retain the originating item across responses.
    let inputItemID: String?
    let callID: String
    let name: String
    /// True only for the continuation created after a temporary native screen
    /// image was acknowledged. The tool layer uses this to ensure untrusted
    /// pixels can request at most the snapshot-bound visual click.
    let visualContextBound: Bool
    /// True for continuations produced from email/provider content. The native
    /// tool boundary prevents that untrusted data from chaining into computer,
    /// memory, relationship, or visual capabilities.
    let untrustedMailContextBound: Bool
    /// True only when asynchronous transcription failed and a context-isolated,
    /// audio-item-only classifier exactly matched the first bounded native call.
    let audioCorroborated: Bool
    /// True when this owner turn has already produced audible Aurora speech.
    /// A successful, visibly self-evident action can then finish without a
    /// redundant second confirmation response.
    let turnAlreadySpoke: Bool
    /// Native causal provenance. This is not supplied by Realtime function
    /// arguments and prevents a continuation from borrowing an earlier turn's
    /// authorization merely because it carries the same input item ID.
    let authorizationSource: ToolAuthorizationSource
    /// Host-derived terminal state of the source audio transcript boundary.
    /// This survives a Realtime transport replacement so a finalized direct
    /// owner handoff cannot be mistaken for an uncommitted call merely because
    /// per-connection transcript caches were cleared.
    let sourceTurnFinalized: Bool

    /// The exact JSON argument string generated by the model.
    let argumentsJSON: String
    /// Exact task-effect binding captured on the original owner-audio helper
    /// call, present only when a later delegate_task matches it.
    let preauthorizedDelegateBinding: String?

    init(
        connectionID: UUID,
        responseID: String,
        inputItemID: String?,
        callID: String,
        name: String,
        visualContextBound: Bool,
        untrustedMailContextBound: Bool,
        audioCorroborated: Bool = false,
        turnAlreadySpoke: Bool,
        authorizationSource: ToolAuthorizationSource = .directOwnerTurn,
        sourceTurnFinalized: Bool,
        argumentsJSON: String,
        preauthorizedDelegateBinding: String? = nil
    ) {
        self.connectionID = connectionID
        self.responseID = responseID
        self.inputItemID = inputItemID
        self.callID = callID
        self.name = name
        self.visualContextBound = visualContextBound
        self.untrustedMailContextBound = untrustedMailContextBound
        self.audioCorroborated = audioCorroborated
        self.turnAlreadySpoke = turnAlreadySpoke
        self.authorizationSource = authorizationSource
        self.sourceTurnFinalized = sourceTurnFinalized
        self.argumentsJSON = argumentsJSON
        self.preauthorizedDelegateBinding = preauthorizedDelegateBinding
    }

    func decodedArguments() throws -> Any {
        guard let data = argumentsJSON.data(using: .utf8) else {
            throw AuroraRealtimeError.invalidFunctionArguments(name: name)
        }
        return try JSONSerialization.jsonObject(with: data)
    }
}

struct RealtimeUserTranscriptEvent {
    let connectionID: UUID
    let itemID: String
    let text: String
    let isFinal: Bool
}

struct RealtimeAssistantTranscriptEvent {
    let connectionID: UUID
    let responseID: String?
    let inputItemID: String?
    let itemID: String
    let text: String
    let isFinal: Bool
}

struct RealtimeAssistantPlaybackOutcome {
    let connectionID: UUID
    let responseID: String
    let inputItemID: String?
    let backgroundTaskDeliveryID: String?
    let itemID: String
    let generatedText: String
    let fullyPlayed: Bool
    let playedMilliseconds: Int?
}

enum RealtimeToolContinuation: Equatable {
    case speak
    /// A validated, host-authored conversational decision is ready. The next
    /// response may speak, but may not select another tool or silently replace
    /// that decision with an assistant-style default.
    case conversationMove
    case delegateAccepted
    /// Realtime produced an invalid structured semantic proposal. Correct the
    /// structure once against the original finalized owner turn without
    /// speaking or widening the authorized effect.
    case delegateRetry
    /// Realtime truthfully classified the turn as a different semantic domain
    /// while calling conversation_move. Retry once with only the correct
    /// semantic function exposed; the host still never reparses owner words.
    case semanticRouteRetry(toolName: String)
    case silent
    case complete
}

enum AuroraRealtimeError: LocalizedError {
    case missingAPIKey
    case invalidToolsJSON
    case toolsMustBeJSONArray
    case invalidFunctionArguments(name: String)
    case unknownFunctionCall
    case noPreviousConfiguration
    case notConnected
    case malformedServerMessage
    case outboundBackpressure
    case server(code: String?, message: String)
    case transport(Error)
    case audio(Error)

    var errorDescription: String? {
        switch self {
        case .missingAPIKey:
            return "Aurora needs an OpenAI API key before voice can begin."
        case .invalidToolsJSON:
            return "Aurora's voice tools are not valid JSON."
        case .toolsMustBeJSONArray:
            return "Aurora's voice tools must be a JSON array."
        case .invalidFunctionArguments(let name):
            return "Aurora received invalid arguments for the \(name) tool."
        case .unknownFunctionCall:
            return "Aurora received a result for a tool call that is no longer active."
        case .noPreviousConfiguration:
            return "Aurora has no previous voice session to reconnect."
        case .notConnected:
            return "Aurora's voice session is not connected."
        case .malformedServerMessage:
            return "Aurora received an unreadable Realtime event."
        case .outboundBackpressure:
            return "Aurora's voice connection fell too far behind live speech."
        case .server(let code, let message):
            if let code, !code.isEmpty {
                return "Realtime error \(code): \(message)"
            }
            return "Realtime error: \(message)"
        case .transport(let error):
            return "Aurora's voice connection ended: \(error.localizedDescription)"
        case .audio(let error):
            return "Aurora's audio path failed: \(error.localizedDescription)"
        }
    }

    /// Copy safe to place directly in the voice-first interface. Detailed API
    /// and operating-system messages remain available through
    /// `localizedDescription` for the private diagnostic journal.
    var userFacingDescription: String {
        switch self {
        case .server:
            return "Aurora couldn't reach the voice service just now."
        case .transport:
            return "Aurora lost the voice connection."
        case .audio:
            return "Aurora's audio path stopped unexpectedly."
        default:
            return errorDescription ?? "Aurora couldn't continue just now."
        }
    }
}

extension RealtimeSessionConfiguration {
    func validatedTools() throws -> [[String: Any]] {
        let trimmedKey = apiKey.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedKey.isEmpty else { throw AuroraRealtimeError.missingAPIKey }
        guard let data = toolsJSON.data(using: .utf8) else {
            throw AuroraRealtimeError.invalidToolsJSON
        }

        let object: Any
        do {
            object = try JSONSerialization.jsonObject(with: data)
        } catch {
            throw AuroraRealtimeError.invalidToolsJSON
        }
        guard let tools = object as? [[String: Any]] else {
            throw AuroraRealtimeError.toolsMustBeJSONArray
        }
        return tools
    }

    func sessionUpdate(tools: [[String: Any]]) -> [String: Any] {
        [
            "type": "session.update",
            "session": [
                "type": "realtime",
                "model": AuroraRealtimeClient.model,
                "output_modalities": ["audio"],
                // Realtime otherwise defaults to an unbounded per-response
                // allowance. This ceiling prevents runaway output while the
                // voice contract—not a tiny hard cap—keeps ordinary turns
                // brief. Longer requested explanations can therefore finish.
                "max_output_tokens": AuroraRealtimeClient.maxResponseOutputTokens,
                "instructions": instructions,
                "truncation": [
                    "type": "retention_ratio",
                    "retention_ratio": AuroraRealtimeClient.conversationRetentionRatio,
                    "token_limits": [
                        "post_instructions": AuroraRealtimeClient.postInstructionConversationTokenLimit,
                    ],
                ],
                "audio": [
                    "input": [
                        "format": [
                            "type": "audio/pcm",
                            "rate": Int(AuroraAudioEngine.sampleRate),
                        ],
                        "noise_reduction": ["type": "near_field"],
                        "transcription": ["model": "gpt-4o-mini-transcribe"],
                        "turn_detection": vad.eventObject,
                    ],
                    "output": [
                        "format": [
                            "type": "audio/pcm",
                            "rate": Int(AuroraAudioEngine.sampleRate),
                        ],
                        "voice": AuroraRealtimeClient.voice,
                    ],
                ],
                "tools": tools,
                // Every owner-audio turn first resolves into an exact Codex
                // task proposal, a bounded conversation_move, or an explicit
                // silent terminal. Only a validated continuation may speak.
                "tool_choice": "required",
                "reasoning": [
                    // High effort materially improves adherence to Aurora's
                    // compact social and self-knowledge boundaries without a
                    // measurable latency penalty in the live probe.
                    "effort": "high",
                ],
            ],
        ]
    }
}
